barplot(table(mtcars$cyl))
plot(x = mtcars$disp, y = mtcars$cyl, type = "s")
plot(x = mtcars$wt, y = mtcars$mpg)
hist(mtcars$mpg)
plot(mtcars$cyl, mtcars$mpg)
plot(as.factor(mtcars$cyl), mtcars$mpg)
hist(mtcars$mpg)
barplot(table(mtcars$cyl))
barplot(table(mtcars$cyl),col='blue',main='cylinders')
barplot(table(mtcars$gear),col='blue',main='gears')
